# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NotEnoughMail's Stuff
description: >- # this means to ignore newlines until "baseurl:"
  NotEnoughMail's site for his online projects: writing, documentation, and possibly more
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://notenoughmail.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: NotEnoughMail

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.10.0

repo: "https://github.com/Notenoughmail/notenoughmail.github.io"
github_user: "Notenoughmail"
github_repo: "notenoughmail.github.io"

# https://just-the-docs.com/docs/customization/
color_scheme: default

favicon_ico: "/assets/favicon.ico"

aux_links:
  GitHub: https://github.com/Notenoughmail/notenoughmail.github.io
  Updates: /feed.xml
  Writing: /writing/feed.xml
  Contact: /contact/

callouts:
  notice:
    title: ‚ö†Ô∏è Notice
    color: yellow
  deprecated:
    title: üóëÔ∏è Deprecated
    color: green
  unstable:
    title: ‚ùó Unstable
    color: red
  prompt:
    title: Prompt
    color: pink
  comment:
    color: grey-dk
  related:
    title: ‚ÑπÔ∏è Related Info
    color: blue-custom

mermaid:
  version: "11.3.0"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md